# Generated by Django 5.0.4 on 2024-06-21 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('cpf_cliente', models.CharField(max_length=14)),
                ('uf_cliente', models.CharField(max_length=2)),
                ('cidade_cliente', models.CharField(blank=True, max_length=100)),
                ('telefone_cliente', models.CharField(blank=True, max_length=20)),
                ('idade_cliente', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Debito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_cliente', models.CharField(max_length=20)),
                ('upag_cliente', models.CharField(max_length=20)),
                ('banco_cliente', models.CharField(max_length=100)),
                ('cod_orgao_cliente', models.CharField(max_length=20)),
                ('valor_cliente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem_cliente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem_cartao_cliente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo_cliente', models.IntegerField()),
                ('situacao_cliente', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'valor_cliente', 'prazo_cliente')},
            },
        ),
    ]
