# Generated by Django 5.0.6 on 2024-07-02 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('uf', models.CharField(max_length=2)),
                ('upag', models.CharField(max_length=50)),
                ('matricula_instituidor', models.CharField(max_length=50)),
                ('situacao_funcional', models.CharField(max_length=50)),
                ('rjur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaDebitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('debito', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=100)),
                ('orgao', models.CharField(max_length=100)),
                ('pmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo', models.IntegerField()),
                ('tipo_contrato', models.CharField(max_length=50)),
                ('contrato', models.CharField(max_length=50)),
                ('creditos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debitos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exc_soma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_calc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bruta_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilz_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('beneficio_bruta_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('beneficio_utilizado_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('beneficio_saldo_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bruta_35', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilz_35', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo_35', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bruta_70', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilz_70', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo_70', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('arq_upag', models.CharField(blank=True, max_length=50, null=True)),
                ('exc_qtd', models.IntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='consultas.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'matricula', 'debito')},
            },
        ),
    ]
