# Generated by Django 5.0.4 on 2024-06-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debito',
            name='desc_cod_orgao_cliente',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade_cliente',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cliente',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idade_cliente',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_cliente',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='uf_cliente',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='debito',
            name='banco_cliente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='debito',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='consultas.cliente'),
        ),
        migrations.AlterField(
            model_name='debito',
            name='cod_orgao_cliente',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='debito',
            name='margem_cartao_cliente',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='debito',
            name='margem_cliente',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='debito',
            name='matricula_cliente',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='debito',
            name='prazo_cliente',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='debito',
            name='situacao_cliente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='debito',
            name='upag_cliente',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='debito',
            name='valor_cliente',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
    ]
