# Generated by Django 5.0.6 on 2024-07-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_cliente_matricula_instituidor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculadebitos',
            name='base_calc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='beneficio_bruta_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='beneficio_saldo_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='beneficio_utilizado_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='bruta_35',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='bruta_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='bruta_70',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='creditos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='debitos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='exc_soma',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='liquido',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='margem',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='pmt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='saldo_35',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='saldo_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='saldo_70',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='utilz_35',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='utilz_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='utilz_70',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
