# Generated by Django 5.0.6 on 2024-07-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_alter_matriculadebitos_base_calc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculadebitos',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='contrato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='creditos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='debito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='debitos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='exc_soma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='liquido',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='margem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='orgao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='pmt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='prazo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculadebitos',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
