# Generated by Django 5.0.6 on 2024-07-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_alter_matriculadebitos_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculadebitos',
            name='prazo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
