# Generated by Django 5.0.6 on 2024-07-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_alter_matriculadebitos_prazo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculadebitos',
            old_name='debito',
            new_name='rubrica',
        ),
        migrations.AlterUniqueTogether(
            name='matriculadebitos',
            unique_together={('cliente', 'matricula', 'rubrica')},
        ),
    ]
