# Generated by Django 5.0.6 on 2024-07-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0007_rename_debito_matriculadebitos_rubrica_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matriculadebitos',
            unique_together=set(),
        ),
    ]
