# Generated by Django 5.0.6 on 2024-07-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img_colab/'),
        ),
        migrations.CreateModel(
            name='RegisterMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cliente', models.CharField(max_length=11)),
                ('valor_est', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('data', models.DateField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_registers', to='funcionarios.ranking')),
            ],
        ),
    ]
