# Generated by Django 5.0.6 on 2024-07-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_ranking_foto_registermoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermoney',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
