# Generated by Django 5.0.4 on 2024-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('ramal', models.CharField(max_length=20)),
                ('campanha', models.CharField(max_length=100)),
            ],
        ),
    ]
